### ISSUE TITLE
macOS Universal 2 Binary Support Request

### ISSUE THREAD

**Issue by jetblackrx89** [Moebytes/Waifu2x-Upscaler#21]
I noticed Intel support got dropped after 0.4.1 for macOS. Could you post Universal 2 binaries? The latest releases are arm64 which are strictly for Apple Silicon based Macs. Thanks.

**Comment by Tenpi** [comment]
Correct, for each platform I usually build the most popular arch, and I have an arm-based mac so the performance is better. But, I can continue building the intel version if there are still lots of people on them.

Universal binary might make a huge filesize so it's better to do it separate but I will have to check.

**Comment by Tenpi** [comment]
v0.5.0 is a universal build

**Comment by Tenpi** [comment]
Looks like I have to build it separately since that module only has arm64 or x64 versions (no universal). Thanks for letting me know.

**Comment by Tenpi** [comment]
Tell me if it works it's in the same release 0.5.0

**Comment by Tenpi** [comment]
Actually nvm I can't seem to build it on x64 anymore, all the dmg's are crashing on startup.

If you still want to use it you can try running from the source.
```sh
git clone https://github.com/Tenpi/Waifu2x-GUI.git
cd waifu2x-gui
npm install
npm start
```
